apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    argocd.argoproj.io/instance: infratoken-service
  name: infratoken-service
  namespace: infratoken
spec:
  selector:
    matchLabels:
      app: infratoken-service
  template:
    metadata:
      labels:
        app: infratoken-service
    spec:
      name: infratoken-service
      containers:
      - name: infratoken-service
        value: Infratoken
        image: 'ghcr.io/marciohideaki/infratokenpoc:latest'
      env:
        - httpGet:
          failureThreshold: 3
          initialDelaySeconds: 10
          path: /healthcheck
          periodSeconds: 10
          port: 3000
          successThreshold: 1
          timeoutSeconds: 5
          livenessProbe: null
          readinessProbe:
            failureThreshold: 3
            httpGet: null
            initialDelaySeconds: 10
            path: /healthcheck
            periodSeconds: 10
            port: 3000
            successThreshold: 1
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 128Mi