apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    argocd.argoproj.io/instance: infratoken-service
  name: infratoken-service
  namespace: staging-infratoken
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infratoken-service
  template:
    metadata:
      name: infratoken-service
      labels:
        app: infratoken-service
    spec:
      containers:
      - name: infratoken-service
        image: 'ghcr.io/marciohideaki/infratokenpoc:latest'
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 128Mi