apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infratoken-service
  namespace: infratoken
spec:
  project: default
  source:
    repoURL: https://github.com/marciohideaki/Infratoken
    path: app
    targetRevision: develop
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infratoken
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true