apiVersion: v1
kind: Service
metadata:
  name: infratoken-service
spec:
  selector:
    app: infratoken-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000  